POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "",
    "name": "",
    "password": "",
    "role": ""
}

###

# @name login

POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###

@token = {{login.response.body.token}}

###

POST http://localhost:3000/band/create 
Authorization: {{token}}
Content-Type: application/json

{
    "name": "",
    "music_genre": "",
    "responsible": ""
}

###
GET http://localhost:3000/band/getBandById/7bf44746-6d61-4c7d-8971-50f9d8cfb920
Authorization: {{token}}
Content-Type: application/json

###

POST http://localhost:3000/show/create 
Authorization: {{token}}
Content-Type: application/json

{
    "week_day": "",
    "start_time": ,
    "end_time": ,
    "band_id": ""
}

###
GET http://localhost:3000/show/getShowByWeekDay/FRIDAY
Authorization: {{token}}



