POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "ariane@gmail.com",
    "name": "Ariane",
    "password": "123456",
    "role": "ADMIN"
}

###

# @name login

POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "email": "ariane@gmail.com",
    "password": "123456"
}

###

@token = {{login.response.body.token}}

###

POST http://localhost:3000/band/create 
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Coldplay",
    "music_genre": "Alternative/indie",
    "responsible": "Chris Martin"
}

###
GET http://localhost:3000/band/getBandById/7bf44746-6d61-4c7d-8971-50f9d8cfb920
Authorization: {{token}}
Content-Type: application/json

###

POST http://localhost:3000/show/create 
Authorization: {{token}}
Content-Type: application/json

{
    "week_day": "FRIDAY",
    "start_time": 20 ,
    "end_time": 23,
    "band_id": "7bf44746-6d61-4c7d-8971-50f9d8cfb920"
}

###
GET http://localhost:3000/show/getShowByWeekDay/FRIDAY
Authorization: {{token}}



